$(function(){
    $(".brick-item").hover(function(){
        $(this).addClass("brick-item-active");
    },function(){
        $(this).removeClass("brick-item-active");
    });
    $(".es-qrcode").click(function(){
        $(this).toggleClass("open")
    });
    $(".editChapter-btn").click(function(){
        $(this).parent().prev().show();
        $(this).parent().prev().prev().hide();
    });
    $(".save-btn").click(function(){
        $(this).parent().hide();
        $(this).parent().prev().show();
    })
});

